name: main python
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Podpięcie Pythona 3.10
        uses: actions/python@v1
        with:
          python-version: '3.10' 

      - name: Tworzenie i uruchomienie wirtualnego środowiska Python
        run: |
          python -m venv venv 
          source venv/bin/activate

      - name: Instalacja dependencji 
        run: pip install -r requirements.txt
  deploy:
    runs-on: ubuntu-latest 
    needs: [build]
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4
      - name: Budowanie apki
        uses: azure/appservice-build@v3 
        with:
          platform: python
          version: 3.10

      - name: Wdrożenie apki do App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'python123asd'
          publish-profile: ${{ $secrets.AZURE_WEB_PROFILE }}
